mode_button = [ 1470, 980,]
mode_list_open_delay = 1.2
mode_pick_delay = 1.5

[mode]
solo_showdown = "Одиночное шоудаун"
duo_showdown = "Парное шоудаун"
trio_showdown = "Тройное шоудаун"
heist = "Ограбление"
bounty = "Охота за баунти"
gem_grab = "Сбор кристаллов"
knockout = "Нокаут"
hot_zone = "Горячая зона"
siege = "Осада"

[solo_showdown]
tile = [ 1600, 700,]
calibrated = false

[duo_showdown]
tile = [ 1600, 790,]
calibrated = false

[trio_showdown]
tile = [ 1600, 880,]
calibrated = false

[heist]
tile = [ 1600, 610,]
calibrated = false

[bounty]
tile = [ 1600, 970,]
calibrated = false

[gem_grab]
tile = [ 1600, 1060,]
calibrated = false

[knockout]
tile = [ 1600, 880,]
calibrated = false

[hot_zone]
tile = [ 1600, 970,]
calibrated = false

[siege]
tile = [ 1600, 610,]
calibrated = false
